### ISSUE TITLE
本プラグインについて

### ISSUE THREAD

**Issue by nnagashima** [matsukei/redmine_send_issue_reply_email#2]
はじめまして
本プラグインについてお聞きしたいことがあります。

これからRedMineを社内利用することを考えており検証を進めていくのですが、
本プラグインはチケットへの返信がRedMine上で出来るプラグインかと存じます。

お聞きしたこととしましては、
相手がメールソフトを用いてRedMineから返信された内容を返信した際に、
同一チケットにチケットとして取り込まれるものなのになりますでしょうか。
それともあくまで返信ができるもののみとなるのでしょうか。

ご回答の程、宜しくお願い致します。

**Comment by maeda-m** [comment]
こんにちは @nnagashima さん。

本プラグインはチケット更新の際に、通常の通知メールとは別に、指定したメールアドレスに対して、注記内容や添付ファイルをメールとして返信できるものです。

> 相手がメールソフトを用いてRedMineから返信された内容を返信した際に、

上記については、Redmine標準機能でメールによるチケット登録および更新ができます。下記のリンクを参考にしてみてください。

* [【SlideShare】Redmineをwebサービスのサポートメールの管理に活用している事例](https://www.slideshare.net/g_maeda/redmine-mailmanage)
* [【Redmine.JP】メールによるチケットの登録](http://redmine.jp/guide/RedmineReceivingEmails/)

最後に宣伝になりますが、@matsukei は Redmine導入／移行／バージョンアップ・運用サポートおよび改善提案などの事業を行っております。ご興味がありましたら下記の弊社HPをご覧いただければと思います。
http://www.matsukei.co.jp/service/redmine_plugin/

**Comment by nnagashima** [comment]
早速のご返信ありがとうございます。

認識確認の為となりますが、
>>相手がメールソフトを用いてRedMineから返信された内容を返信した際に、
>上記については、Redmine標準機能でメールによるチケット登録および更新ができます。下記のリンクを参考にしてみてください。

ということは返信した際には別で新規にチケットが発行されてしまうという認識で宜しかったでしょうか。


以上、宜しくお願い致します。

**Comment by maeda-m** [comment]
> ということは返信した際には別で新規にチケットが発行されてしまうという認識で宜しかったでしょうか。

ここらへんの振る舞いは Redmine本体の [app/models/mail_handler.rb](https://github.com/redmine/redmine/blob/master/app/models/mail_handler.rb) と [プラグインのテスト](https://github.com/matsukei/redmine_send_issue_reply_email/blob/master/test/functional/issues_controller_test.rb#L289) を読むか、実際に動かすと分かります。

大雑把に言ってしまうと、本プラグイン経由のメールを相手が返信した場合、チケットは新規作成されず、チケットの注記として更新されます。これは Redmine標準機能の `redmine:email:receive_XXX` タスクでは、メール内容を読み取った際に、タスク実行時の前提条件（特に権限回り）を満たし、かつ、次のどちらかの条件を満たした場合にチケットを更新するためです。

1. メールの件名にチケット番号があるか？
    * 本プラグインはメールから新規作成されたチケットであれば、自動的にメール件名にチケット番号を付加します。
2. Redmine 経由で送信されたメールに対する返信か？
    * 本プラグインはRedmine 経由であることをメール情報に付加しています。

**Comment by itf-takasaki** [comment]
本日、8-1-2-1 長時間録音 の開始をお願いします。

7/10
- 機器のシーン・フォルダは「会話」に設定。
- Cubaseでtone波形出力
- 録音スイッチで開始（tone波形録音)
- 26時間40分で録音は止まります。

7/13
- PCにUSB接続
- RECORDER\TALK フォルダにWMAファイルがあります。
- ノッチフィルタでノイズを確認

26時間40分のWMAファイルが出来ていない時は電池の容量不足なので、アルカリ電池の購入お願いします。
立替伝票で清算して下さい。
10時間再生はおそらく大丈夫なので、26時間の録音時のみアルカリ電池を使用して下さい。
